[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
source = "core/lua_reload.lua"
before = "main.lua"
name = "lua_reload"

[[patches]]
[patches.pattern]
target = 'main.lua'
pattern = "if (love.system.getOS() == 'OS X' ) and (jit.arch == 'arm64' or jit.arch == 'arm') then jit.off() end"
position = 'after'
match_indent = true
payload = '''
lua_reload = require('lua_reload')
lua_reload.Inject()
'''

[[patches]]
[patches.pattern]
target = 'engine/controller.lua'
pattern = 'if key == "r" and not G.SETTINGS.paused then'
position = 'at'
match_indent = true
payload = '''
if key == 'm' then
	if self.held_key_times[key] > 0.9 then
		if G.STAGE == G.STAGES.RUN then G.FUNCS.go_to_menu() end
		SMODS.reload()
	else
		self.held_key_times[key] = self.held_key_times[key] + dt
	end
elseif key == 'q' then
	if self.held_key_times[key] > 1.2 then
		SMODS.restart_game()
	else
		self.held_key_times[key] = self.held_key_times[key] + dt
	end
elseif key == "r" and not G.SETTINGS.paused then
'''