name: Compile PS1 to EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install PS2EXE
      shell: powershell
      run: |
        Install-Module -Name ps2exe -Scope CurrentUser -Force
        Import-Module ps2exe
    - name: Compile PS1 script to EXE
      shell: powershell
      run: |
        ps2exe .\injector.ps1 steamodded_PS_injector.exe
    - name: Rename Files
      shell: powershell
      run: Rename-Item -Path ./injector.ps1 -NewName steamodded_PS_injector.ps1
    - name: Upload EXE to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ps_files
        path: |
          ./steamodded_PS_injector.exe
          ./steamodded_PS_injector.ps1
