name: Compile Python to EXE with Nuitka

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install MinGW (C compiler)
      run: |
        choco install mingw  # Installs MinGW via Chocolatey
    - name: Verify GCC Version
      run: gcc --version
    - name: Install Nuitka and dependencies
      run: pip install --force-reinstall nuitka==1.9.4 requests urllib3
    - name: Compile Python script to EXE
      run: python -m nuitka --assume-yes-for-downloads --report=out.xml --standalone --onefile --include-data-dir=core=./core --include-data-dir=debug=./debug --include-data-dir=loader=./loader steamodded_injector.py
    - name: Upload EXE to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: steamodded_injector
        path: |
          ./steamodded_injector.dist/*
          out.xml
